[book]
authors = ["Niko Matsakis"]
language = "en"
multilingual = false
src = "src"
title = "The Rust Language Design Team"

[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 0

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html.redirect]
"/rust-2018/edition-changes.html" = "index.html"
"/priorities.html" = "initiatives/priorities.html"
"/project_groups.html" = "initiatives/active.html"
"/proposing_a_project.html" = "initiatives/proposing.html"
"/initiatives.html" = "how_to/propose.html"
"/initiatives/faq.html" = "how_to/propose.html"
"/initiatives/priorities.html" = "how_to/propose.html"
"/initiatives/process/checklists.html" = "how_to/propose.html"
"/initiatives/process/roles/liaison.html" = "how_to/propose.html"
"/initiatives/process/roles/owner.html" = "how_to/propose.html"
"/initiatives/process/roles.html" = "how_to/propose.html"
"/initiatives/process/stages/development.html" = "how_to/propose.html"
"/initiatives/process/stages/experimental.html" = "how_to/experiment.html"
"/initiatives/process/stages/feature_complete.html" = "how_to/propose.html"
"/initiatives/process/stages/inactive.html" = "how_to/propose.html"
"/initiatives/process/stages/proposal.html" = "how_to/propose.html"
"/initiatives/process/stages/stabilized.html" = "how_to/propose.html"
"/initiatives/process/stages.html" = "how_to/propose.html"
"/initiatives/process.html" = "how_to/propose.html"
"/initiatives/stable.html" = "how_to/propose.html"
